name: atlas_digital_fmabc
description: "Atlas Digital Interativo de Biologia Tecidual. Aplicativo multiplataforma para exploração interativa de imagens citológicas escaneadas em altíssima resolução. O Atlas Digital FMABC simula a experiência de observação por microscópio, oferecendo recursos de ampliação, rotação, espelhamento, navegação fluida, anotações e organização de conteúdos por tópicos. Voltado para alunos e professores, proporciona uma interface intuitiva e acessível para estudo e ensino de citologia."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.273
  go_router: ^16.2.4
  flutter_svg: ^2.2.1
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/ # Logo da FMABC e do Atlas Digital
    - assets/images/bg/ # Imagens de fundo e de decoração
